spring.mvc.pathmatch.matching-strategy: ant_path_matcher

logging.level.br.com.saude.imc: DEBUG

spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:forum
    username: sa
    password:

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
        hibernate:
            show_sql: true
            format_sql: true